### PR TITLE
Change toHTML rendering to allow custom HTML content inside cells and not just text

### LINKED ISSUE #319: Rendering of IMG, IFrame appears to be broken
These 2 classes if presented in dataframe should be rendered in HTML to img and iframe tags. For me it didn't work. Our youtube example relies on this feature, so I went and checked if the previously working example is still intact, but the answer is no for IntelliJ project. In datalore its even worse, it breaks completely when i run cell with "load", although it doesn't even use any iframe or anything like that, only special rendering of URL. At this point i decided not to investigate Datalore issue further.

### PR DESCRIPTION
**Pull request by koperagen**
fixes #319

### CODE REVIEW

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/dataTypes/IMG.kt [hunk 1]
```diff
@@ -23,6 +23,6 @@ public data class IMG(
         if (height != null) style.append("height:${height}px;")
         if (maxWidth != null) style.append("max-width:${maxWidth}px;")
         if (maxHeight != null) style.append("max-height:${maxHeight}px;")
-        return """<img src="$src" style="$style"}/>"""
+        return """<img src="$src" style="$style"/>"""
```
Comment (Jolanrensen) [inline core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/dataTypes/IMG.kt:26]: wow good find

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/html.kt [hunk 2]
```diff
@@ -514,6 +516,8 @@ private fun AnyFrame.getColumnsHeaderGrid(): List<List<ColumnWithPathWithBorder<
 internal fun DataFrameHtmlData.print() = println(this)
 
 /**
+ * By default, cell content is formatted as text
```
Comment (Jolanrensen) [inline core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/html.kt:519]: very helpful comment, thanks!

**Review by Jolanrensen — APPROVED** [review]
cool :D
