### PR TITLE
Fixed formatting

### LINKED ISSUE #315: Make method declaration for four APIs more consistent
- [x] Be sure that all methods are ordered by the same order (all, ColumnSelector, String, Reference, KProperties)
- [x] Be sure that there are no missed APIs
- [x] Reformat the code
- [x] Add spaces correctly between functions
- [x] add some docs if new method was added or removed

### PR DESCRIPTION
**Pull request by zaleslaw**
Fixes #315

### CODE REVIEW

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/tsv.kt [hunk 1]
```diff
@@ -28,7 +28,7 @@ public class TSV : SupportedDataFrameFormat {
     }
 }
 
-private val tabChar = '\t'
+private const val tabChar = '\t'
 
 public fun DataFrame.Companion.readTSV(
```
Comment (Jolanrensen) [inline core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/tsv.kt:33]: While you're at it, could you check this file and probably csv.kt for named arguments? I see many usages of readDelim with 10+ params and no names, which will break stuff quickly upon refactoring or the addition of extra params in the future

Comment (zaleslaw) [reply core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/tsv.kt:33]: Looks like we need to fix and discuss the case with the named arguments separately.

Because in many cases it just doubles the code without additional sense.

Comment (Jolanrensen) [reply core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/tsv.kt:33]: I think it's always sensible, especially when there are multiple arguments with the same type involved.
