### PR TITLE
Util functions fixes

### LINKED ISSUE #1389: Add KDocs for a set of tiny functions
- [ ] `any` https://github.com/Kotlin/dataframe/blob/master/core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/any.kt
- [ ] `between` https://github.com/Kotlin/dataframe/blob/master/core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/between.kt
- [ ] `associate` https://github.com/Kotlin/dataframe/blob/master/core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/associate.kt
- [ ] `asSequence` https://github.com/Kotlin/dataframe/blob/master/core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/asSequence.kt
- [ ] `asIterable` https://github.com/Kotlin/dataframe/blob/master/core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/asIterable.kt

Highly likely, JUnit test doesn't exist, please create to cover the main scenario at least before writing Documentation

### PR DESCRIPTION
**Pull request by AndreiKingsley**
KDocs and tests for a set of small util functions + deprecate obsolete ones.
Closes #1389

### CODE REVIEW

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/any.kt [hunk 1]
```diff
@@ -2,18 +2,46 @@ package org.jetbrains.kotlinx.dataframe.api
...
+/**
+ * Returns `true` if at least one element in this [DataColumn] satisfies the given [predicate].
+ *
+ * This is a convenience alias that delegates to [Iterable.any] on the column's [values].
+ *
+ * @param predicate A lambda function that takes a value from the column
+ * and returns `true` if it matches the condition.
+ * @return `true` if at least one element matches the [predicate], `false` otherwise.
+ * @see [DataColumn.all]
+ * @see [DataColumn.filter]
```
Comment (Jolanrensen) [inline core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/any.kt:21]: I don't think filter and count are very relevant, only `all`

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/any.kt [hunk 2]
```diff
@@ -2,18 +2,46 @@ package org.jetbrains.kotlinx.dataframe.api
...
+ *
+ * ### Example
+ * ```kotlin
+ * // Check if there is at least one row where "age" is greater than 18
+ * val hasAdults = df.any { age > 18 }
+ * ```
+ *
+ * @param predicate A [RowFilter] lambda that takes a [DataRow] (as both `this` and `it`)
+ * and returns `true` if the row should be considered a match.
+ * @return `true` if at least one row satisfies the [predicate], `false` otherwise.
```
Comment (Jolanrensen) [inline core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/any.kt:43]: this should then also link to DataFrame.all

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/between.kt [hunk 3]
```diff
@@ -5,6 +5,18 @@ import org.jetbrains.kotlinx.dataframe.impl.between
 
 // region DataColumn
 
+/**
+ * Returns a [DataColumn] of [Boolean] values indicating whether each element
```
Comment (Jolanrensen) [inline core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/between.kt:9]: each element in `[this]`

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/tail.kt [hunk 4]
```diff
@@ -1,9 +1,12 @@
 package org.jetbrains.kotlinx.dataframe.api
 
 import org.jetbrains.kotlinx.dataframe.DataFrame
+import org.jetbrains.kotlinx.dataframe.util.TAIL
+import org.jetbrains.kotlinx.dataframe.util.TAIL_REPLACE
 
 // region DataFrame
 
+@Deprecated(TAIL, ReplaceWith(TAIL_REPLACE), DeprecationLevel.ERROR)
```
Comment (Jolanrensen) [inline core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/tail.kt]: I would keep `tail` as shortcut for `takeLast(5)`, since we also have `head` as a shortcut for `take(5)`. It's easy to get a quick glance at the beginning or end of a dataframe

File: core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/samples/api/Create.kt [hunk 5]
```diff
@@ -79,7 +78,8 @@ class Create : TestBase() {
         // SampleEnd
     }
 
-    @Test
+    // Not used anymore
```
Comment (Jolanrensen) [inline core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/samples/api/Create.kt]: please remove then :)

File: examples/kotlin-dataframe-plugin-example/src/main/kotlin/org/jetbrains/kotlinx/dataframe/examples/plugin/Main.kt [hunk 6]
```diff
@@ -6,9 +6,11 @@ import org.jetbrains.kotlinx.dataframe.api.add
 import org.jetbrains.kotlinx.dataframe.api.convert
 import org.jetbrains.kotlinx.dataframe.api.convertTo
 import org.jetbrains.kotlinx.dataframe.api.filter
+import org.jetbrains.kotlinx.dataframe.api.insert
```
Comment (Jolanrensen) [inline examples/kotlin-dataframe-plugin-example/src/main/kotlin/org/jetbrains/kotlinx/dataframe/examples/plugin/Main.kt]: unused imports

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/any.kt (hunk 1 above)
Comment (AndreiKingsley) [reply core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/any.kt:21]: Why? IMHO these functions are really related.

Comment (AndreiKingsley) [reply core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/any.kt:21]: Since they all operate on column values with a Boolean condition.

Comment (zaleslaw) [reply core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/any.kt:21]: Agree with Andrew here

**Review by zaleslaw — APPROVED** [review]

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/any.kt (hunk 1 above)
Comment (Jolanrensen) [reply core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/any.kt:21]: well so does `takeWhile`, `dropWhile` and I can think of some more.

I would only group `all {}` and `any {}` since they both reduce to a single boolean:
`Column<T>.function(predicate: (T) -> Boolean): Boolean`
 (`none {}` would be here too, if we had it... do we?)
