### PR TITLE
KDocs fixes for `distinct` and `distinctBy`

### LINKED ISSUE #1434: Distinct KDocs are wrong
The KDocs of `distinct` actually show the docs of `distinctBy {}`:

Image

This is not how `distinct { cols }` functions. Distinct with columns is a shortcut for `select { cols }.distinctBy { all() }`.
So, 
`distinctBy`: Removes duplicated rows based on the specified columns.
`distinct`: Selects the specified columns keeping only distinct rows

### PR DESCRIPTION
**Pull request by Allex-Nik**
Fixes #1434

The documentation for the `distinct` function with parameters described the functionality of `distinctBy`: it suggested that `distinct` removes duplicated rows omitting the fact that it also selects the specified columns and the result contains only these columns.

In this PR I:
* Fixed this issue by changing descriptions of `distinct`
* Added `distinctBy` to DocumentationUrls
* Made some other minor fixes

### CODE REVIEW

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt [hunk 1]
```diff
@@ -23,24 +25,26 @@ import kotlin.reflect.KProperty
...
  *
  * @see [Selecting Columns][SelectSelectingOptions].
  * @see {@include [DocumentationUrls.Distinct]}
+ * @see {@include [DocumentationUrls.DistinctBy]}
  */
 @ExcludeFromSources
 @Suppress("ClassName")
 private interface DistinctDocs {
     interface DISTINCT_PARAM
+    interface DISTINCT_RETURN
```
Comment (Allex-Nik) [inline core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt:61]: Does it make sense to add it here? I introduced this tag to separate cases when we return a DataFrame with distinct rows and when we return a DataFrame which contains only selected columns and distinct rows.

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt [hunk 2]
```diff
@@ -52,15 +56,21 @@ public fun <T> DataFrame<T>.distinct(): DataFrame<T> = distinctBy { all() }
...
  */
 @Refine
 @Interpretable("Distinct0")
 public fun <T, C> DataFrame<T>.distinct(columns: ColumnsSelector<T, C>): DataFrame<T> = select(columns).distinct()
 
 /**
  * {@include [DistinctDocs]}
- * {@set PHRASE_ENDING the specified columns}.
+ * {@set DESCRIPTION It selects the specified columns and keeps only distinct rows based on these selected columns}
+ * {@set [DistinctDocs.DISTINCT_PARAM] @param [columns] The names of the columns to select
```
Comment (Allex-Nik) [inline core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt]: I changed the description of the parameter for some functions to mention that it is also used to select columns.

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt [hunk 3]
```diff
@@ -87,7 +103,10 @@ public fun <T> DataFrame<T>.distinct(vararg columns: AnyColumnReference): DataFr
 
 /**
  * {@include [DistinctDocs]}
+ * {@set NAME DistinctBy}
  * {@set PHRASE_ENDING the specified columns}.
+ * {@set [DistinctDocs.DISTINCT_PARAM] @param [columns]
```
Comment (Allex-Nik) [inline core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt]: I specified this explicitly for this and the following functions (instead of keeping the default option in the common section in `DistinctDocs`) to avoid the issue with `[columns]` I mentioned in the description of the PR.

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt [hunk 4]
```diff
@@ -23,24 +25,27 @@ import kotlin.reflect.KProperty
 // region DataFrame
 
 /**
- * ## The Distinct Operation
+ * ## The {@get NAME Distinct} Operation
```
Comment (AndreiKingsley) [inline core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt]: Remove header, we decided not to add headers at all

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt (hunk 1 above)
Comment (AndreiKingsley) [reply core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt:61]: Yes, it's ok

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt [hunk 5]
```diff
@@ -23,24 +25,27 @@ import kotlin.reflect.KProperty
...
  *
- * It removes duplicated rows based on {@get PHRASE_ENDING}.
+ * {@get DESCRIPTION It removes duplicated rows based on {@get PHRASE_ENDING}}.
```
Comment (AndreiKingsley) [inline core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt]: Please, change in all kdocs "It removes .." -> "Removes .."

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt [hunk 6]
```diff
@@ -23,24 +25,27 @@ import kotlin.reflect.KProperty
...
  *
- * __NOTE:__ The rows in the resulting [DataFrame] are in the same order as they were in the original [DataFrame].
+ * __NOTE:__ The [rows][DataRow] in the resulting [DataFrame] are in the same order
```
Comment (AndreiKingsley) [inline core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt]: Nice, but let's remove "__NOTE:__"

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt [hunk 7]
```diff
@@ -23,24 +25,27 @@ import kotlin.reflect.KProperty
...
+ * as they were in the original [DataFrame].
  *
- * {@get [DISTINCT_PARAM] @param [columns]
- * The names of the columns to consider for evaluating distinct rows.}
+ * {@get [DISTINCT_PARAM]}
  *
- * @return A new DataFrame containing only distinct rows.
+ * {@get [DISTINCT_RETURN] @return A new [DataFrame] containing only distinct rows.}
  *
  * @see [Selecting Columns][SelectSelectingOptions].
```
Comment (AndreiKingsley) [inline core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt]: Let's rewrite this section with our template: https://github.com/Kotlin/dataframe/blob/5d6b7af77de4d92de9b1b3adb686e8af23eacae2/core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/convert.kt#L109

Something like that

```
See also [distinctBy], that (write difference here)

 @include [SelectingColumns.ColumnGroupsAndNestedColumnsMention]
 
 See [Selecting Columns][ConvertSelectingOptions].
 
 For more information: {@include [DocumentationUrls.Distinct]}
```

**Comment by AndreiKingsley** [comment]
@Allex-Nik To avoid this problem with `[columns]` you can write `[\columns]` instead. We use this trick in many places.

I'd even say it's better to write `[\columns]` in such places always.

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt [hunk 8]
```diff
@@ -87,7 +104,10 @@ public fun <T> DataFrame<T>.distinct(vararg columns: AnyColumnReference): DataFr
 
 /**
  * {@include [DistinctDocs]}
+ * {@set NAME DistinctBy}
  * {@set PHRASE_ENDING the specified columns}.
```
Comment (AndreiKingsley) [inline core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt]: change to` [\columns]` here and in other places

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt [hunk 9]
```diff
@@ -23,24 +25,27 @@ import kotlin.reflect.KProperty
...
- * __NOTE:__ The rows in the resulting [DataFrame] are in the same order as they were in the original [DataFrame].
+ * __NOTE:__ The [rows][DataRow] in the resulting [DataFrame] are in the same order
+ * as they were in the original [DataFrame].
  *
- * {@get [DISTINCT_PARAM] @param [columns]
- * The names of the columns to consider for evaluating distinct rows.}
+ * {@get [DISTINCT_PARAM]}
  *
- * @return A new DataFrame containing only distinct rows.
+ * {@get [DISTINCT_RETURN] @return A new [DataFrame] containing only distinct rows.}
```
Comment (Jolanrensen) [inline core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt]: Seems you can "lift out" the `@return`, as you include it everywhere you set `[DISTINCT_RETURN]`

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt [hunk 10]
```diff
@@ -23,24 +25,27 @@ import kotlin.reflect.KProperty
...
  *
  * @see [Selecting Columns][SelectSelectingOptions].
  * @see {@include [DocumentationUrls.Distinct]}
```
Comment (Jolanrensen) [inline core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt]: never used `@see` like that :o seems to work well!

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt (hunk 9 above)
Comment (Jolanrensen) [reply core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt]: (and you never set `[DISTINCT_RETURN]` to empty)

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt [hunk 11]
```diff
@@ -52,15 +57,21 @@ public fun <T> DataFrame<T>.distinct(): DataFrame<T> = distinctBy { all() }
 
 /**
  * {@include [DistinctDocs]}
- * {@set PHRASE_ENDING the specified columns}.
+ * {@set DESCRIPTION It selects the specified columns and keeps only distinct rows based on these selected columns}
+ * {@set [DistinctDocs.DISTINCT_PARAM] @param [columns] The names of the columns to select
```
Comment (Jolanrensen) [inline core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt]: it's not "The names of the columns" though, it's a columns selector. Check how we write the `@param` of columnsSelectors in other operations :)

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt (hunk 2 above)
Comment (Jolanrensen) [reply core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt]: it's also not "the names" here

Comment (Jolanrensen) [reply core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt]: but as this function is deprecated, you can probably remove the kdocs altogether

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt (hunk 5 above)
Comment (Jolanrensen) [reply core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt]: Please make sure all `@get/@set` keys are `[references]`. This will work too, but references are refactor- and typo-safe :)

Comment (Jolanrensen) [reply core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt]: See https://github.com/Kotlin/dataframe/blob/master/KDOC_PREPROCESSING.md#arg-interfaces

**Comment by Jolanrensen** [comment]
> Specified the parameter explicitly for every function to avoid incorrect resolution of the columns parameter mentioned in DistinctDocs

TL;DR: write it like `[columns\]`

Long explanation:

Whenever some KDocs is `@include`d, all references mentioned in that doc are expanded to their fully qualified path, if possible. This solves the issue that a reference to `[a]` in one doc is not necessarily resolvable as `[a]` in another doc. But it may be resolvable as `[a][path.to.a]`.

If a reference cannot be found, it's left unchanged as `[a]`.

Unfortunately, this system is not perfect (resolving symbols by path in kotlin myself is hard XD), so when you write
```kt
/** @param [columns] The names of the columns to consider for evaluating distinct rows. */
interface DistinctDocs

/** @include [DistinctDocs] */
public fun <T> DataFrame<T>.distinctBy...
```

KoDEx tries to find `[columns]` in the scope of `DistinctDocs`, finds it, and expands it to `[columns][org.jetbrains.kotlinx.dataframe.columns]` before including it at `distinctBy()`.

Luckily, we have the [`\` escape character](https://github.com/Kotlin/dataframe/blob/67a1ef868ed3b0c2e4e90e6c7ca3729df39952db/KDOC_PREPROCESSING.md#-escape-character) :) which allows us to stop KoDEx from doing "clever" things. These are removed from the KDocs in the last phase. These allow you to 'break' tags like `\@inlude X`, or `\$something`, or references like `\[columns]` so they aren't processed anymore :). (You can put the `\` anywhere in the reference I believe, actually)

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt (hunk 11 above)
Comment (Jolanrensen) [reply core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt]: It's probably best to just write the `@param` line at the bottom of this KDoc, as each overload needs a different line of text for it. Yes, it will be below the `@return` then, but the IDE still renders it well.

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt (hunk 5 above)
Comment (Allex-Nik) [reply core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt]: Then I need to include `DESCRIPTION` and `PHRASE_ENDING` into `DistinctDocs` like this, right?

```kotlin
private interface DistinctDocs {
    interface DISTINCT_PARAM

    interface DISTINCT_RETURN

    interface DESCRIPTION

    interface PHRASE_ENDING

    interface FUNCTION
}
```

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt (hunk 3 above)
Comment (Allex-Nik) [reply core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt]: After the solution with `[columns\]` was pointed out, the KDocs for deprecated functions were deleted, and the parameter descriptions were individualized for different parameters, this is no longer relevant.

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt (hunk 11 above)
Comment (Allex-Nik) [reply core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt]: I fixed the descriptions of the parameters, thank you :)
Why is it best to write the `@param` line at the bottom, below the `@return`? If I set the `@return` after the `@param`, everything seems to work for all cases in the file.

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt (hunk 8 above)
Comment (Allex-Nik) [reply core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt]: Is it fine to do `[columns\]`? I saw `[columns\]` in other functions I checked, and the effect seems to be the same.

**Comment by Allex-Nik** [comment]
> TL;DR: write it like `[columns\]`
> 
> Long explanation:

@Jolanrensen, thank you! I understand :)

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt (hunk 8 above)
Comment (Jolanrensen) [reply core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt]: yes, doesn't matter where you put the `\` :) as long as you break the reference

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt [hunk 12]
```diff
@@ -23,45 +29,60 @@ import kotlin.reflect.KProperty
 // region DataFrame
 
 /**
- * ## The Distinct Operation
+ * {@get [DESCRIPTION] Removes duplicated rows based on {@get [PHRASE_ENDING]}}.
```
Comment (Jolanrensen) [inline core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt]: interesting, I've never used a `{@get}` inside the "default" section of another `{@get}` XD but it works :). Did you know you can also write `$[PRASE_ENDING]` btw? just an alternative notation, does the same.

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt [hunk 13]
```diff
@@ -23,45 +29,60 @@ import kotlin.reflect.KProperty
...
 private interface DistinctDocs {
     interface DISTINCT_PARAM
+
+    interface DISTINCT_RETURN
+
+    interface DESCRIPTION
+
+    interface PHRASE_ENDING
+
+    interface FUNCTION
```
Comment (Jolanrensen) [inline core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt]: I usually write a tiny comment (no KDoc) next to each parameter, to clarify what they mean

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt [hunk 14]
```diff
@@ -23,45 +29,60 @@ import kotlin.reflect.KProperty
...
  * {@include [DistinctDocs]}
- * {@set PHRASE_ENDING all columns}.
- * {@set [DistinctDocs.DISTINCT_PARAM]}
+ * {@set [PHRASE_ENDING] all columns}
+ * {@set [DISTINCT_PARAM]}
  */
 public fun <T> DataFrame<T>.distinct(): DataFrame<T> = distinctBy { all() }
 
 /**
  * {@include [DistinctDocs]}
```
Comment (Jolanrensen) [inline core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt]: None of the tags in this KDoc need `{}` around them, as they are not inside another line. It doesn't hurt though, so feel free to write it how you think is best

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt (hunk 12 above)
Comment (Allex-Nik) [reply core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt]: I didn't know about `$[PRASE_ENDING]`, it looks better, I used it :)

Comment (Jolanrensen) [reply core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt]: you can also provide a "default" with that notation, but it needs to be small, as spaces split it up already, like `$key=default` :)

Comment (Allex-Nik) [reply core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt]: Nice! I implemented it as well, thank you!
Now `$[PHRASE_ENDING]=all`, and in some places I just replace "all" with "the specified", so "columns" is no longer a part of the `[PHRASE_ENDING]` and is only a part of `[DESCRIPTION]` :)

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt (hunk 13 above)
Comment (Allex-Nik) [reply core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt]: Done

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt (hunk 14 above)
Comment (Allex-Nik) [reply core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt]: Done

**Review by AndreiKingsley — APPROVED** [review]
Nice!
