### PR TITLE
Reusage schemas fix

### LINKED ISSUE #1222: Jupyter: Data schema generation bug with mixed nullability of similarly named column
Can be reproduced on 1.0.0-Beta2:

```kts
val df1 = dataFrameOf(
    "group" to columnOf(
        "a" to columnOf(1, null, 3),
    )
)
val df2 = dataFrameOf(
    "group" to columnOf(
        "a" to columnOf(1, 2, 3),
    )
)
```
produces:
```kt
// for df1

@DataSchema(isOpen = false)
interface _DataFrameType1 {
    val a: Int?
}

@DataSchema
interface _DataFrameType {
    val group: _DataFrameType1
}

// for df2

@DataSchema(isOpen = false)
interface _DataFrameType3 {
    val a: Int
}

@DataSchema
interface _DataFrameType2 : _DataFrameType {
    override val group: _DataFrameType3 // Type of 'group' is not a subtype of overridden property 'val group: _DataFrameType1' defined in '_DataFrameType'
}
```

What I suspect was meant to be generated is something like this:
```kt
@DataSchema(isOpen = false)
interface _DataFrameType1 {
    val a: Int?
}

@DataSchema
interface _DataFrameType {
    val group: _DataFrameType1
}

// for df2

@DataSchema(isOpen = false)
interface _DataFrameType3 : _DataFrameType1 { // now the non-nullable variant extends the nullable variant
    override val a: Int // requires override
}

@DataSchema
interface _DataFrameType2 : _DataFrameType {
    override val group: _DataFrameType3
}
```

### PR DESCRIPTION
**Pull request by Jolanrensen**
Fixes #1222 by replacing the `strictlyEqualNestedSchemas` parameter by a more explicit `ComparisonMode`.

Comparing two schemas in `LENIENT` mode can return `IsSuper`, `IsDerived`, `IsEqual`, or `None`.
Compating in `STRICT` mode can only return `IsEqual` or `None`, because the schema's need to exactly match.
`STRICT_FOR_NESTED_SCHEMAS` works in `LENIENT` mode for the top-level, but `STRICT` for nested schemas. This is often used in Jupyter notebooks, to prevent nested types from extending each other and thus avoid a potential comparison explosion. (There could be a lot of nested types)

Also, added documentation everywhere

Requires tiny patch in the compiler plugin

### CODE REVIEW

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/schema/DataFrameSchema.kt [hunk 1]
```diff
@@ -1,12 +1,17 @@
...
 
     /**
      * By default generated markers for leafs aren't used as supertypes: @DataSchema(isOpen = false)
-     * strictlyEqualNestedSchemas = true takes this into account for internal codegen logic
+     * [ComparisonMode.STRICT_FOR_NESTED_SCHEMAS] takes this into account for internal codegen logic
      */
-    public fun compare(other: DataFrameSchema, strictlyEqualNestedSchemas: Boolean = false): CompareResult
+    public fun compare(
+        other: DataFrameSchema,
+        comparisonMode: ComparisonMode = STRICT_FOR_NESTED_SCHEMAS,
```
Comment (koperagen) [inline core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/schema/DataFrameSchema.kt]: i think LENIENT should be default for more visibility - easier to see where our "special" codegen mode STRICT_FOR_NESTED_SCHEMAS handling is used

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/schema/ColumnSchema.kt [hunk 2]
```diff
@@ -88,37 +88,27 @@ public abstract class ColumnSchema {
...
-    public fun compare(other: ColumnSchema): CompareResult = compare(other, false)
-
-    internal fun compareStrictlyEqualNestedSchemas(other: ColumnSchema): CompareResult = compare(other, true)
-
-    private fun compare(other: ColumnSchema, strictlyEqualNestedSchemas: Boolean): CompareResult {
+    public fun compare(other: ColumnSchema, comparisonMode: ComparisonMode = STRICT_FOR_NESTED_SCHEMAS): CompareResult {
         if (kind != other.kind) return CompareResult.None
         if (this === other) return CompareResult.Equals
         return when (this) {
             is Value -> compare(other as Value)
```
Comment (koperagen) [inline core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/schema/ColumnSchema.kt]: Seems odd that comparison mode is not used here. How you tell the difference between nullable and non-nullable column?

**Comment by Jolanrensen** [comment]
> Seems good, but it's quite hard to review with many stylistic / non-functional changes :(

Sorry, I just had no clue what was going on before refactoring, let alone debug how it should behave. Hopefully the new approach expresses the intention behind the code better :)

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/schema/DataFrameSchema.kt (hunk 1 above)
Comment (Jolanrensen) [reply core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/schema/DataFrameSchema.kt]: I agree :)

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/schema/ColumnSchema.kt (hunk 2 above)
Comment (Jolanrensen) [reply core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/schema/ColumnSchema.kt]: That's true, I had it at one point, but it wasn't in the implementation before... Let's see what breaks if I add it back

Comment (Jolanrensen) [reply core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/schema/ColumnSchema.kt]: Ah, the same behavior was achieved by `if (comparison != Equals && comparisonMode == STRICT) None else comparison` in the other file, but I improved it now so `ColumnSchema.Value` now also has a `comparisonMode` argument and the "strictness increase" is better explained.
