### PR TITLE
fix camelCase

### LINKED ISSUE #988: `renameToCamelCase` works is not as expected
it did from ID       ITEM  PRICE ORDER_DATE ->  iD       iTEM  pRICE  oRDERDATE"

_Originally posted by @zaleslaw in https://github.com/Kotlin/dataframe/pull/986#discussion_r1870008458_

It handles mostly the typical use-case, when we are reading from CSV file, created somewhere in Python, but when we are reading from the databases, it mostly using the capital letters, which we need to lowercase

### PR DESCRIPTION
**Pull request by AndreiKingsley**
* fixes #988 
Add kdocs and tests, also fixed code from https://github.com/Kotlin/dataframe/pull/986#discussion_r1870008458_.

### CODE REVIEW

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/rename.kt [hunk 1]
```diff
@@ -50,21 +48,42 @@ public class RenameClause<T, C>(internal val df: DataFrame<T>, internal val colu
 /**
  * ## Rename to camelCase
  *
- * This function renames all columns to `camelCase` by replacing all [delimiters][DELIMITERS_REGEX]
- * and converting the first char to lowercase.
- * Even [DataFrames][DataFrame] inside [FrameColumns][FrameColumn] are traversed recursively.
+ * This function renames all columns in this [DataFrame] to `camelCase` format.
```
Comment (Jolanrensen) [inline core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/rename.kt:51]: *the `camelCase` format

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/Utils.kt [hunk 2]
```diff
@@ -337,28 +337,110 @@ internal fun <T : Comparable<T>> T.between(left: T, right: T, includeBoundaries:
...
+ * "justNumbers123" -> "justNumbers123"
+ * "Just_Special\$Chars!!" -> "justSpecialChars"
+ * "singleword" -> "singleword"
+ * "word_with_underscores_and-dashes" -> "wordWithUnderscoresAndDashes"
+ * "10-20-aa" -> "10_20Aa"
+ * ```
+ *
+ * @return trhe formatted string in lowerCamelCase.
+ */
+public fun String.toCamelCaseByDelimiters(delimiters: Regex = CAMEL_DEFAULT_DELIMITERS_REGEX): String =
```
Comment (Jolanrensen) [inline core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/Utils.kt:387]: this pollutes the public String scope. Maybe keep it internal for now?

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/Utils.kt [hunk 3]
```diff
@@ -337,28 +337,110 @@ internal fun <T : Comparable<T>> T.between(left: T, right: T, includeBoundaries:
         this > left && this < right
     }
 
-private const val DELIMITERS = "[_\\s]"
-public val DELIMITERS_REGEX: Regex = DELIMITERS.toRegex()
-public val DELIMITED_STRING_REGEX: Regex = ".+$DELIMITERS.+".toRegex()
+// Single regex to split words by non-alphanumeric characters, camelCase, and numbers
```
Comment (Jolanrensen) [inline core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/Utils.kt:341]: newline

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/Utils.kt [hunk 4]
```diff
@@ -337,28 +337,110 @@ internal fun <T : Comparable<T>> T.between(left: T, right: T, includeBoundaries:
...
 
-internal val CAMEL_REGEX = "(?<=[a-zA-Z])[A-Z]".toRegex()
+internal val CAMEL_DEFAULT_DELIMITERS_REGEX =
+    "[^a-zA-Z0-9]+|(?<=[a-z])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])|(?<=\\d)(?=[a-zA-Z])|(?<=[a-zA-Z])(?=\\d)".toRegex()
```
Comment (Jolanrensen) [inline core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/Utils.kt:343]: Hmm, I'm wondering whether "a-zA-Z" correctly catches all letters. There are more letters than just a-z; there are letters like óäàãæ, not to mention other alphabets. Best to use the "\p" notation in Regex to catch all cases. I used something similar in KoDEx to recreate the Kotlin spec for an "identifier" in Regex: https://github.com/Jolanrensen/KoDEx/blob/97abf961186d2bb6c75756e9ec1946dd853e721e/kodex-common/src/main/kotlin/nl/jolanrensen/kodex/docContent/DocContent.kt#L319 There are even \p notations for uppercase and lowercase letters I believe.

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/Utils.kt [hunk 5]
```diff
@@ -337,28 +337,110 @@ internal fun <T : Comparable<T>> T.between(left: T, right: T, includeBoundaries:
...
 
-public fun String.toCamelCaseByDelimiters(delimiters: Regex): String = split(delimiters).joinToCamelCaseString()
+/**
+ * Converts a string into lowerCamelCase using [delimiters].
+ *
+ * - Splits words using a unified regex that handles delimiters.
```
Comment (Jolanrensen) [inline core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/Utils.kt:348]: Maybe specify shortly what this means, something like "Splits words on any characters that are not letters or digits" (that's true right?), it's clearer that way.

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/Utils.kt [hunk 6]
```diff
@@ -337,28 +337,110 @@ internal fun <T : Comparable<T>> T.between(left: T, right: T, includeBoundaries:
...
+ * - If the string does not contain any letters or numbers, it remains unchanged.
+ * - Places underscore ("_") between numbers.
```
Comment (Jolanrensen) [inline core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/Utils.kt:350]: only between numbers that were split before

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/Utils.kt [hunk 7]
```diff
@@ -337,28 +337,110 @@ internal fun <T : Comparable<T>> T.between(left: T, right: T, includeBoundaries:
...
+ * "UPPERCASE" -> "uppercase"
+ * "alreadyCamelCased" -> "alreadyCamelCased"
+ * "justNumbers123" -> "justNumbers123"
+ * "Just_Special\$Chars!!" -> "justSpecialChars"
+ * "singleword" -> "singleword"
+ * "word_with_underscores_and-dashes" -> "wordWithUnderscoresAndDashes"
+ * "10-20-aa" -> "10_20Aa"
+ * ```
+ *
+ * @return trhe formatted string in lowerCamelCase.
```
Comment (Jolanrensen) [inline core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/Utils.kt:385]: typo

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/Utils.kt [hunk 8]
```diff
@@ -337,28 +337,110 @@ internal fun <T : Comparable<T>> T.between(left: T, right: T, includeBoundaries:
...
+ */
+public fun String.toCamelCaseByDelimiters(delimiters: Regex = CAMEL_DEFAULT_DELIMITERS_REGEX): String =
+    if (!this.any { it.isLetter() || it.isDigit() }) {
+        this // If the string has no letters, return it unchanged
+    } else {
+        split(delimiters)
+            .filter { it.isNotBlank() }
+            .map { it.lowercase() }
+            .joinNumbers("_")
```
Comment (Jolanrensen) [inline core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/Utils.kt:394]: maybe we can make this an argument of the function, could be useful to change later if we need to :)

**Review by zaleslaw — APPROVED** [review]
Great! Thanks for fixing this and docs update

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/Utils.kt [hunk 9]
```diff
@@ -337,28 +337,110 @@ internal fun <T : Comparable<T>> T.between(left: T, right: T, includeBoundaries:
...
+            .joinToCamelCaseString()
+    }
+
+/**
+ * Joins consecutive numbers in a list with the given [separator].
+ */
+private fun List<String>.joinNumbers(separator: CharSequence): List<String> {
```
Comment (Jolanrensen) [inline core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/Utils.kt:401]: Hmm this seems a bit overcomplicated. It's not really clear what this function does and it's hard to check due to its complexity.
(What I think it does is [a1, 123, 345, bcd] -> [a1, 123_345, bcd], is that correct? This is then joined to "a1123_345Bcd". Actually, I think a1 and 123 should remain split as well.)

Wouldn't it be a lot simpler to perform a map-with-next and let `joinWithCamelCaseString` handle the joining part? Something like:
```kt
list.mapIndexed { i, current ->
    val next = list.getOrNull(i + 1) ?: return@mapIndexed current
    if (current.last().isDigit() && next.first().isDigit()) {
        current + "_"
    } else {
        current
    }
}
```
This would do [a1, 123, 345, bcd] -> [a1_, 123_, 345, bcd], after which they can be joined together like "a1_123_345Bcd"

File: core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/impl/ToCamelCase.kt [hunk 10]
```diff
@@ -0,0 +1,74 @@
...
+            "___!!!___",
+            "1000.2000.3000",
+            "UPPERCASE",
+            "alreadyCamelCased",
+            "justNumbers123",
+            "Just_Special\$Chars!!",
+            "singleword",
+            "word_with_underscores_and-dashes",
+            "10-20-aa",
+            "ROOM_1.11",
```
Comment (Jolanrensen) [inline core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/impl/ToCamelCase.kt:37]: Could you also add some special characters, like æ or letters from other alphabets?

File: dataframe-openapi-generator/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/utils.kt [hunk 11]
```diff
@@ -18,7 +17,7 @@ internal fun String.withoutTopInterfaceName(topInterfaceName: ValidFieldName): S
         this
     }
 
-internal fun String.snakeToLowerCamelCase(): String = toCamelCaseByDelimiters(DELIMITERS_REGEX)
```
Comment (Jolanrensen) [inline dataframe-openapi-generator/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/utils.kt:21]: Let's just deprecate this function or remove it

**Review by Jolanrensen — CHANGES_REQUESTED** [review]

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/Utils.kt (hunk 9 above)
Comment (AndreiKingsley) [reply core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/Utils.kt:401]: It assumes that all numbers and strings are separated, I'll write a comment.

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/Utils.kt (hunk 2 above)
Comment (AndreiKingsley) [reply core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/Utils.kt:387]: This is used in another module.

File: dataframe-openapi-generator/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/utils.kt (hunk 11 above)
Comment (AndreiKingsley) [reply dataframe-openapi-generator/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/utils.kt:21]: I'm hesitating because it's used in the implementation, I don't understand why and how it should work so I'm just afraid of breaking something

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/rename.kt [hunk 12]
```diff
@@ -50,21 +48,42 @@ public class RenameClause<T, C>(internal val df: DataFrame<T>, internal val colu
...
+ *
+ * All delimiters between words are removed, words are capitalized except for the first one.
+ * Places underscore between numbers.
+ * If the string does not contain any letters or numbers, it remains unchanged.
```
[the remark this answers is not in the document]
Comment (Jolanrensen) [reply core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/rename.kt:55]: oh you're right

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/Utils.kt (hunk 9 above)
Comment (Jolanrensen) [reply core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/Utils.kt:401]: aah that was unclear indeed. Still, it might do with some simplification :)

File: dataframe-openapi-generator/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/utils.kt (hunk 11 above)
Comment (Jolanrensen) [reply dataframe-openapi-generator/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/utils.kt:21]: alright

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/Utils.kt (hunk 9 above)
Comment (AndreiKingsley) [reply core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/Utils.kt:401]: I'd prefer to separate digit logic

File: core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/Utils.kt (hunk 2 above)
Comment (AndreiKingsley) [reply core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/Utils.kt:387]: I can use friend modules

Comment (Jolanrensen) [reply core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/Utils.kt]: No it's fine for now. We will consider friend modules later probably, when we find out a safe way to use them.
