### PR TITLE
The KING of Reverts

### LINKED ISSUE #1595: H2 database without dialect is unsupported
Repro in notebooks:
```
%use database
#%%
val src = createDataSource("jdbc:h2:mem:testdb")
#%%
%use dataframe(1.0.0-dev-8941), kandy(0.8.3-dev-92, 0.5.1-dev-2)

#%%
DataFrame.readSqlQuery(src, """SELECT 1""")
```
Error:
java.lang.IllegalArgumentException: Unsupported database type in the url: jdbc:h2:mem:testdb. Only MySQL, MariaDB, MSSQL and PostgreSQL are supported!
	at org.jetbrains.kotlinx.dataframe.io.db.UtilKt.extractDBTypeFromConnection(util.kt:54)

Similar connection string are used in our guides/kdocs:
https://kotlin.github.io/dataframe/h2.html#read
https://github.com/Kotlin/kotlin-notebook-integrations/blob/master/integrations/database/database-api/src/main/kotlin/org/jetbrains/kotlinx/jupyter/database/apis.kt#L47

Worth to improve error message, or maybe provide default dialect or implement new DbType

### PR DESCRIPTION
**Pull request by zaleslaw**
Closes #1595

### CODE REVIEW

File: dataframe-jdbc/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/db/util.kt [hunk 1]
```diff
@@ -21,78 +29,88 @@ public fun extractDBTypeFromConnection(connection: Connection): DbType {
...
- * @throws [RuntimeException] if the url is null.
+ * @throws [SQLException] if the url is null.
+ * @throws [IllegalArgumentException] if the URL specifies an unsupported database type.
  */
 public fun extractDBTypeFromUrl(url: String?): DbType {
-    if (url != null) {
-        val helperH2Instance = H2()
-        return when {
-            helperH2Instance.dbTypeInJdbcUrl in url -> createH2Instance(url)
+    url ?: throw SQLException("Database URL could not be null.")
```
Comment (koperagen) [inline dataframe-jdbc/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/db/util.kt:93]: Nullable `url: String?` here catched my eye. What happens if you remove nullabiliy `url: String`? Do we need it here?
